//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: client_chat.proto
namespace PROTO_CHAT
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TCM_CHAT_PUBLIC")]
  public partial class TCM_CHAT_PUBLIC : global::ProtoBuf.IExtensible
  {
    public TCM_CHAT_PUBLIC() {}
    
    private string _Text;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Text", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Text
    {
      get { return _Text; }
      set { _Text = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TCM_CHAT_PRIVATE_ID")]
  public partial class TCM_CHAT_PRIVATE_ID : global::ProtoBuf.IExtensible
  {
    public TCM_CHAT_PRIVATE_ID() {}
    
    private string _RoleId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"RoleId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string RoleId
    {
      get { return _RoleId; }
      set { _RoleId = value; }
    }
    private string _Text;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Text", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Text
    {
      get { return _Text; }
      set { _Text = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TCM_CHAT_PRIVATE_NAME")]
  public partial class TCM_CHAT_PRIVATE_NAME : global::ProtoBuf.IExtensible
  {
    public TCM_CHAT_PRIVATE_NAME() {}
    
    private string _RoleName;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"RoleName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string RoleName
    {
      get { return _RoleName; }
      set { _RoleName = value; }
    }
    private string _Text;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Text", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Text
    {
      get { return _Text; }
      set { _Text = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TSM_CHAT")]
  public partial class TSM_CHAT : global::ProtoBuf.IExtensible
  {
    public TSM_CHAT() {}
    
    private uint _Type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Type
    {
      get { return _Type; }
      set { _Type = value; }
    }
    private string _RoleId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"RoleId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string RoleId
    {
      get { return _RoleId; }
      set { _RoleId = value; }
    }
    private string _RoleName;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"RoleName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string RoleName
    {
      get { return _RoleName; }
      set { _RoleName = value; }
    }
    private uint _Vip;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"Vip", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Vip
    {
      get { return _Vip; }
      set { _Vip = value; }
    }
    private string _Text;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"Text", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Text
    {
      get { return _Text; }
      set { _Text = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TSM_CHAT_ERROR")]
  public partial class TSM_CHAT_ERROR : global::ProtoBuf.IExtensible
  {
    public TSM_CHAT_ERROR() {}
    
    private PROTO_CHAT.EChatError _Error;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Error", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public PROTO_CHAT.EChatError Error
    {
      get { return _Error; }
      set { _Error = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TSM_SYSMSG")]
  public partial class TSM_SYSMSG : global::ProtoBuf.IExtensible
  {
    public TSM_SYSMSG() {}
    
    private string _Text;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Text", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Text
    {
      get { return _Text; }
      set { _Text = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TSM_CHAT_LOCKINFO")]
  public partial class TSM_CHAT_LOCKINFO : global::ProtoBuf.IExtensible
  {
    public TSM_CHAT_LOCKINFO() {}
    
    private ulong _UnLockTime;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"UnLockTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong UnLockTime
    {
      get { return _UnLockTime; }
      set { _UnLockTime = value; }
    }
    private string _Reason;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Reason", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Reason
    {
      get { return _Reason; }
      set { _Reason = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"CLT_CMD")]
    public enum CLT_CMD
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"CM_CHAT_PUBLIC", Value=0)]
      CM_CHAT_PUBLIC = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CM_CHAT_PRIVATE_ID", Value=1)]
      CM_CHAT_PRIVATE_ID = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CM_CHAT_PRIVATE_NAME", Value=2)]
      CM_CHAT_PRIVATE_NAME = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"SVR_CMD")]
    public enum SVR_CMD
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SM_CHAT", Value=0)]
      SM_CHAT = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SM_CHAT_ERROR", Value=1)]
      SM_CHAT_ERROR = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SM_SYSMSG", Value=2)]
      SM_SYSMSG = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SM_CHAT_LOCKINFO", Value=3)]
      SM_CHAT_LOCKINFO = 3
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"EChatType")]
    public enum EChatType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"emChatType_Public", Value=0)]
      emChatType_Public = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"emChatType_Private", Value=1)]
      emChatType_Private = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"emChatType_Private_self", Value=2)]
      emChatType_Private_self = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"_CHAT_TYPE_COUNT_", Value=3)]
      _CHAT_TYPE_COUNT_ = 3
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"EChatError")]
    public enum EChatError
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"EChatError_Offline", Value=1)]
      EChatError_Offline = 1
    }
  
}