//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: client_friend.proto
namespace PROTO_FRIEND
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TSM_FRIEND_DATA")]
  public partial class TSM_FRIEND_DATA : global::ProtoBuf.IExtensible
  {
    public TSM_FRIEND_DATA() {}
    
    private int _relation_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"relation_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int relation_id
    {
      get { return _relation_id; }
      set { _relation_id = value; }
    }
    private PROTO_FRIEND.FRIEND_DATA_OPE _operation;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"operation", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public PROTO_FRIEND.FRIEND_DATA_OPE operation
    {
      get { return _operation; }
      set { _operation = value; }
    }
    private readonly global::System.Collections.Generic.List<string> _role_id = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(3, Name=@"role_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> role_id
    {
      get { return _role_id; }
    }
  
    private readonly global::System.Collections.Generic.List<PROTO_FRIEND.RELATION_TYPE> _type = new global::System.Collections.Generic.List<PROTO_FRIEND.RELATION_TYPE>();
    [global::ProtoBuf.ProtoMember(4, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<PROTO_FRIEND.RELATION_TYPE> type
    {
      get { return _type; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _time = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(5, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> time
    {
      get { return _time; }
    }
  
    private readonly global::System.Collections.Generic.List<string> _name = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(6, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> name
    {
      get { return _name; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _head_icon = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(7, Name=@"head_icon", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> head_icon
    {
      get { return _head_icon; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _vip_level = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(8, Name=@"vip_level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> vip_level
    {
      get { return _vip_level; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _role_level = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(9, Name=@"role_level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> role_level
    {
      get { return _role_level; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _offline_time = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(10, Name=@"offline_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> offline_time
    {
      get { return _offline_time; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TCM_UPDATE_RELATION")]
  public partial class TCM_UPDATE_RELATION : global::ProtoBuf.IExtensible
  {
    public TCM_UPDATE_RELATION() {}
    
    private int _relation_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"relation_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int relation_id
    {
      get { return _relation_id; }
      set { _relation_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TCM_ADD_FRIEND")]
  public partial class TCM_ADD_FRIEND : global::ProtoBuf.IExtensible
  {
    public TCM_ADD_FRIEND() {}
    
    private string _role_name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"role_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string role_name
    {
      get { return _role_name; }
      set { _role_name = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TSM_FRIEND_LIST")]
  public partial class TSM_FRIEND_LIST : global::ProtoBuf.IExtensible
  {
    public TSM_FRIEND_LIST() {}
    
    private readonly global::System.Collections.Generic.List<PROTO_FRIEND.SVR_RESULT> _result = new global::System.Collections.Generic.List<PROTO_FRIEND.SVR_RESULT>();
    [global::ProtoBuf.ProtoMember(1, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<PROTO_FRIEND.SVR_RESULT> result
    {
      get { return _result; }
    }
  
    private readonly global::System.Collections.Generic.List<PROTO_FRIEND.TSM_FRIEND_DATA> _friend_list = new global::System.Collections.Generic.List<PROTO_FRIEND.TSM_FRIEND_DATA>();
    [global::ProtoBuf.ProtoMember(2, Name=@"friend_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<PROTO_FRIEND.TSM_FRIEND_DATA> friend_list
    {
      get { return _friend_list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"CLT_CMD")]
    public enum CLT_CMD
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"CM_REQUEST", Value=1)]
      CM_REQUEST = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CM_ACCEPT", Value=2)]
      CM_ACCEPT = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CM_REFUSE", Value=3)]
      CM_REFUSE = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CM_IGNORE", Value=4)]
      CM_IGNORE = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CM_DELETE", Value=5)]
      CM_DELETE = 5
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"SVR_CMD")]
    public enum SVR_CMD
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SM_UPDATE_FRIEND", Value=1)]
      SM_UPDATE_FRIEND = 1
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"SVR_RESULT")]
    public enum SVR_RESULT
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SE_SUCCESS", Value=1)]
      SE_SUCCESS = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SE_ALREADY_REQUESTED", Value=2)]
      SE_ALREADY_REQUESTED = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SE_IS_FRIEND", Value=3)]
      SE_IS_FRIEND = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SE_IN_REQUESING_LIST", Value=4)]
      SE_IN_REQUESING_LIST = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SE_REQUEST_FULL", Value=5)]
      SE_REQUEST_FULL = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SE_MY_FRIEND_LIST_FULL", Value=6)]
      SE_MY_FRIEND_LIST_FULL = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SE_OPPOSITE_FRIEND_FULL", Value=7)]
      SE_OPPOSITE_FRIEND_FULL = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SE_INVALID_NAME", Value=8)]
      SE_INVALID_NAME = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SE_TIMEOUT", Value=9)]
      SE_TIMEOUT = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SE_INVALID_REQUEST_PARAM", Value=10)]
      SE_INVALID_REQUEST_PARAM = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SE_SERVER_ERROR", Value=11)]
      SE_SERVER_ERROR = 11
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"RELATION_TYPE")]
    public enum RELATION_TYPE
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"REL_T_WAIT", Value=1)]
      REL_T_WAIT = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REL_T_REFUSE", Value=2)]
      REL_T_REFUSE = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REL_T_WE_ARE_FRIEND", Value=3)]
      REL_T_WE_ARE_FRIEND = 3
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"FRIEND_DATA_OPE")]
    public enum FRIEND_DATA_OPE
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"FDO_INIT", Value=1)]
      FDO_INIT = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FDO_NEW", Value=2)]
      FDO_NEW = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FDO_UPDATE", Value=3)]
      FDO_UPDATE = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FDO_DELETE", Value=4)]
      FDO_DELETE = 4
    }
  
}